[project]
name = "personal-workspace-app"
version = "0.1.0"
description = ""
authors = [
    {name = "sunquanhu",email = "sunquanhu@hulupos.com"}
]
readme = "README.md"
requires-python = "^3.12"
dependencies = [
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn[standard] (>=0.52.4,<0.53.0)",
    "pydantic (>=2.13.5,<3.0.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "sqlalchemy[asyncio] (>=2.0.52,<3.0.0)",
    "asyncpg (>=0.31.0,<0.32.0)",
    "alembic (>=1.19.1,<2.0.0)"
]

[tool.poetry]
packages = [{include = "personal_workspace_app", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "ruff (>=0.16.5,<0.17.0)",
    "mypy (>=2.3.1,<3.0.0)"
]
